blank_issues_enabled: false
contact_links:
  - name: ðŸ“š Documentation
    url: https://muhammad-fiaz.github.io/downloader.zig/
    about: Check the documentation for guides, API reference, and examples
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/muhammad-fiaz/downloader.zig/discussions
    about: Ask questions and discuss ideas with the community
